// Humanized review templates for Team Excellent Career Institute, Patna.
// Generated by composing realistic student fragments into unique combinations.
// Never repeats the same review twice within a session (handled in UI).

export type Category = "JEE" | "NEET";

const OPENERS: Record<Category, string[]> = {
  JEE: [
    "Honestly, joining Team Excellent Career Institute was the best decision I took for my JEE prep.",
    "Main Patna ka student hoon and trust me, ye institute JEE ke liye game changer hai.",
    "After a wasted dropper year, Team Excellent finally gave my JEE prep a proper direction.",
    "Bihar Board se aaya tha, JEE ka level dekh ke dar gaya tha — yahan aake confidence wapas mila.",
    "Patna mein bahut jagah try ki, but Team Excellent Career Institute jaisa serious environment kahin nahi mila.",
    "I was honestly losing hope before joining — sir log ne literally meri JEE journey turn around kar di.",
    "Yaar sach bolu toh, IIT JEE ke liye Patna mein isse better coaching milna mushkil hai.",
  ],
  NEET: [
    "Team Excellent Career Institute ne meri NEET prep ko bilkul next level pe le gaya.",
    "Patna mein NEET coaching dhundh rahi thi months se, finally yahan aake sukoon mila.",
    "Dropper year tha mera, family ka pressure tha — yahan ke teachers ne sambhal liya.",
    "Honestly speaking, best medical coaching in Patna agar koi hai toh ye hai.",
    "NEET ka syllabus dekh ke pehle ghabra gaya tha, but sir logo ne strategy itni clean banayi.",
    "Bihar se NEET crack karna easy nahi hai, but yahan ke faculty ne sab possible bana diya.",
    "Mera bio weak tha, ab mock tests mein consistent 320+ aa raha hai — credit goes to this institute.",
  ],
};

const BODIES: Record<Category, string[]> = {
  JEE: [
    "Physics ke concepts itne deeply samjhaye jaate hain ki PYQs khud-ba-khud ban jaate hain.",
    "Maths ka level genuinely advanced hai, JEE Advanced pattern ke according.",
    "Doubt solving sessions sabse strong point hai — koi bhi doubt latka nahi rehta.",
    "Mock tests JEE Main aur Advanced dono ke exact pattern pe based hote hain.",
    "Faculty IITian hain aur shortcuts nahi, proper concept padhate hain.",
    "Test series ki ranking system se khud ka actual level pata chal jata hai.",
    "Chapter-wise tests ke baad detailed discussion hoti hai, har mistake clear ho jati hai.",
  ],
  NEET: [
    "Biology padhane ka style itna interesting hai ki ek bhi topic boring nahi lagta.",
    "Chemistry ke organic reactions ab mujhe ratne nahi pad rahe, logically samajh aa raha hai.",
    "NCERT line-by-line cover karte hain, jo NEET ke liye sabse zaroori hai.",
    "Weekly tests aur AIIMS pattern ke mocks regularly hote hain.",
    "Bio diagrams, mnemonics, sab kuch revision-friendly notes mein milta hai.",
    "Doubt clearing sessions ke baad sir personally bhi attention dete hain.",
    "Class ke baad bhi teachers WhatsApp pe doubts solve karte hain, that's rare.",
  ],
};

const EMOTIONS = [
  "Sach bolu toh, yahan aake mera confidence wapas aaya.",
  "Family pressure tha but yahan ke environment ne mujhe sambhal liya.",
  "Hostel life tough thi, but institute family jaisa lagta hai.",
  "Dropper hoon, second attempt hai — pehli baar lag raha hai ki ho jayega.",
  "Mock test mein har week improvement saaf dikh raha hai.",
  "Teachers genuinely care karte hain, sirf padhane tak limited nahi hain.",
  "Competition ka dar tha, ab woh ek motivation ban gaya hai.",
  "Bihar Board background ka complex tha, ab woh gap fully fill ho gaya.",
];

const KEYWORDS: Record<Category, string[]> = {
  JEE: [
    "best coaching for JEE in Patna",
    "top IIT JEE coaching in Bihar",
    "best faculty for IIT JEE in Patna",
    "JEE Main coaching in Patna",
    "best coaching for droppers in Patna",
  ],
  NEET: [
    "best NEET coaching in Patna",
    "best medical coaching in Patna",
    "best institute for NEET preparation",
    "top NEET faculty in Bihar",
    "top coaching institute in Bihar",
  ],
};

const CLOSERS = [
  "Highly recommended to anyone serious about their prep.",
  "Agar Patna mein ho aur serious ho prep ke liye, ek baar visit zaroor karo.",
  "10/10 from my side, no second thoughts.",
  "If you want results, this is the place. Simple.",
  "Strongly suggest this to every aspirant in Bihar.",
  "Thank you Team Excellent for everything 🙏",
  "Worth every single rupee and every single hour.",
];

function pick<T>(arr: T[], seen: Set<string>, key: string): T {
  // Try to pick something not yet used in this review
  const available = arr.filter((v) => !seen.has(`${key}:${String(v)}`));
  const pool = available.length ? available : arr;
  const item = pool[Math.floor(Math.random() * pool.length)];
  seen.add(`${key}:${String(item)}`);
  return item;
}

// Track reviews already shown in this browser session to avoid repetition
const SESSION_KEY = "tec_seen_reviews_v1";

function getSeen(): Set<string> {
  if (typeof window === "undefined") return new Set();
  try {
    return new Set(JSON.parse(localStorage.getItem(SESSION_KEY) || "[]"));
  } catch {
    return new Set();
  }
}

function saveSeen(seen: Set<string>) {
  if (typeof window === "undefined") return;
  try {
    const arr = Array.from(seen).slice(-500);
    localStorage.setItem(SESSION_KEY, JSON.stringify(arr));
  } catch {
    /* ignore */
  }
}

export function generateReview(category: Category): string {
  const seen = getSeen();
  const fragmentsUsed = new Set<string>();

  for (let attempt = 0; attempt < 20; attempt++) {
    const opener = pick(OPENERS[category], fragmentsUsed, "o");
    const body1 = pick(BODIES[category], fragmentsUsed, "b1");
    const body2 = pick(BODIES[category], fragmentsUsed, "b2");
    const emotion = pick(EMOTIONS, fragmentsUsed, "e");
    const keyword = pick(KEYWORDS[category], fragmentsUsed, "k");
    const closer = pick(CLOSERS, fragmentsUsed, "c");

    const variations = [
      `${opener} ${body1} ${emotion} ${body2} Genuinely ${keyword} hai. ${closer}`,
      `${opener}\n\n${body1} ${body2}\n\n${emotion} Without exaggeration, ${keyword}. ${closer}`,
      `${opener} ${emotion}\n\n${body1} ${body2} Mere experience mein ye ${keyword} hai. ${closer}`,
    ];
    const text = variations[Math.floor(Math.random() * variations.length)];
    const hash = simpleHash(text);

    if (!seen.has(hash)) {
      seen.add(hash);
      saveSeen(seen);
      return text;
    }
  }

  // Extremely unlikely fallback
  return `${OPENERS[category][0]} ${BODIES[category][0]} ${CLOSERS[0]}`;
}

function simpleHash(s: string): string {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return String(h);
}

// ---- Google Maps deep linking ----

// TODO: Replace with the institute's actual Google Place ID for direct review deep-link.
// Find via https://developers.google.com/maps/documentation/places/web-service/place-id
export const GOOGLE_PLACE_ID = "";

const SEARCH_QUERY = "Team Excellent Career Institute Patna";

export function getReviewUrl(): string {
  if (GOOGLE_PLACE_ID) {
    return `https://search.google.com/local/writereview?placeid=${GOOGLE_PLACE_ID}`;
  }
  // Fallback: open Google Maps search for the place; user taps "Write a review"
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(SEARCH_QUERY)}`;
}

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    const ta = document.createElement("textarea");
    ta.value = text;
    ta.style.position = "fixed";
    ta.style.opacity = "0";
    document.body.appendChild(ta);
    ta.select();
    const ok = document.execCommand("copy");
    document.body.removeChild(ta);
    return ok;
  } catch {
    return false;
  }
}